name: Manual Issue Transer Action Test
on:
  issues:
    types:
      - labeled

jobs:
  test-action:
    runs-on: self-hosted

    steps:
      - name: Transfer Issue & Create Stub
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          router: md:biobb_gromacs